### ISSUE TITLE
按照步骤部署，到测试时 post create.php时报500错误

### ISSUE THREAD

**Issue by ogump** [zeruniverse/QBotWebWrap#1]
QzoneLiker点run后就卡死了，我在服务器上查看process表也没有数据记录上去

**Comment by ogump** [comment]
原来是sqllink第十行array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8'); 报Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'。

**Comment by ogump** [comment]
我来给像我一样的php小白补坑。。装完php后要装gd和pdo。。

**Comment by zeruniverse** [comment]
这个项目里的qqparking能用么？
