### ISSUE TITLE
点完run后未出现二维码界面

### ISSUE THREAD

**Issue by dysl357085918** [zeruniverse/QBotWebWrap#2]
按照步骤部署的，点完run后网页倒是跳转了，但二维码并未出现。。地址：http://sg.shanliang.moe/qq

**Comment by zeruniverse** [comment]
SmartQQ可能會封禁服務器ip段，請先使用該服務器代理看看能不能手動登上smartqq

**Comment by dysl357085918** [comment]
挂代理是可以登录的，另外点完run后log框也未有显示。

**Comment by zeruniverse** [comment]
1.登陸vps 用 ps aux| grep 看看python是否運行。
2.去/var/log/httpd下查看php錯誤日誌

**Comment by dysl357085918** [comment]
搞定了，谢谢(⌒▽⌒)

**Comment by xborner** [comment]
能讲下怎么解决的吗，也是一样配置完无法弹出二维码，确定可以登录smartqq，查询python进程发现每一次查询进程pid都在变，另外单独qliker脚本是可以运行的

**Comment by zeruniverse** [comment]
@xborner 你查python每次都在变估计是你用了 `ps aux|grep python`, 你查到在变的不是`python`进程而是`grep python`的进程。

我感觉你应该是运行权限不够，你可以看下你的PHP log

**Comment by xborner** [comment]
@zeruniverse 启用了exec函数后可以使用了，但是扫码登录后会提示：ERROR Could not find an available JavaScript runtime. php没报错，js环境也安装了。

**Comment by zeruniverse** [comment]
我没在任何地方使用NodeJS 请确保你的所有代码被PHP执行了
