### ISSUE TITLE
小黄鸡的那个登陆失败

### ISSUE THREAD

**Issue by yeket** [zeruniverse/QBotWebWrap#3]
qqbot.py[line:107] ERROR Get mibao_res Url Error.
Fri, 12 Aug 2016 21:37:45  qqbot.py[line:554] INFO PTWebQQ: d62f5fa3f5ad9247ce30f0ab5b2f913c52d87065ccb1d7a2f3d0e1bd24c77692
Fri, 12 Aug 2016 21:37:45  qqbot.py[line:566] CRITICAL 登录失败，正在重试

**Comment by zeruniverse** [comment]
就输出就这么点信息不会吧……

建议先以下步骤：
1.点赞鸡能否正常启动
2.如果能，用你部署qbot的服务器代理，试试浏览器能不能登陆smartqq

**Comment by zeruniverse** [comment]
Closed due to no response
