### ISSUE TITLE
关于与smartQQbot这个相同地方

### ISSUE THREAD

**Issue by wnark** [zeruniverse/QBotWebWrap#5]
你好，我原本搭好之后一直出现不了二维码，先默认是我的问题，现在是我需要实现
“!delete {ha}{哈哈}可以删除该内容。吐槽内容本地保存在data/tucao_save/中”
这个插件功能，请问您是否删除了这个插件，没有的话启动目录是在哪？
谢谢。

**Comment by zeruniverse** [comment]
@coldeve TX协议更改造成问题，现已修复
