### ISSUE TITLE
配置好后无法弹出二维码和log

### ISSUE THREAD

**Issue by llllzimran** [zeruniverse/QBotWebWrap#7]
![10](https://user-images.githubusercontent.com/29818326/28771958-420409a8-7617-11e7-93ec-7cbeaba42caf.png)
centos系统下，三个都是这样，已用服务器终端ping通w.qq.com

**Comment by zeruniverse** [comment]
抱歉 近期比较忙各种被邮件轰炸。。。

建议看下PHP的log， cent os 在/var/log/httpd里面

我的系统也是centos，我能跑
